# Generated by Django 4.0.6 on 2023-02-03 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_createdat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-createdAt']},
        ),
    ]
